spring:
  datasource:
    password: 123
    username: ahrorjon
    url: jdbc:postgresql://localhost:5432/vouchercart
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true